### ISSUE TITLE
Secret keys are publicly visible

### ISSUE THREAD

**Issue by kinshukdua** [kushv16/Mumbai_Police#6]
Hi, your secret keys, email and password is publicly visible on Github, can I submit a PR for removing the same?

**Comment by kushv16** [comment]
Hi Kinshukdua, The secrets file contained the old email & password, they were updated later. Removing the file from the repository slipped from my mind. Thank you for letting me know.

**Comment by kinshukdua** [comment]
@kushv16 You might be better off rebasing repo if the email and password are important, since people can still go back to previous commits to check out the files.

**Comment by kushv16** [comment]
@kinshukdua Sure will do that. Thanks :)
